# Generated by Django 5.0.1 on 2024-11-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trusted_devices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
