# Generated by Django 5.0.1 on 2024-11-18 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('filer', '0017_image__transparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.folder'),
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filer.file'),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
