# Generated by Django 5.0.1 on 2024-11-19 00:49

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_folder_alter_content_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to=apps.content.models.content_file_path),
        ),
    ]
