# Generated by Django 5.0.1 on 2024-11-15 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_options_contentshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'permissions': (('can_view_shared_content', 'Can view shared content'), ('can_edit_shared_content', 'Can edit shared content'), ('can_delete_shared_content', 'Can delete shared content'), ('can_share_content', 'Can share content'))},
        ),
        migrations.AlterModelOptions(
            name='contentshare',
            options={'ordering': ('-shared_at',)},
        ),
        migrations.RenameField(
            model_name='contentshare',
            old_name='created_at',
            new_name='shared_at',
        ),
        migrations.RemoveField(
            model_name='content',
            name='exclude_from_legacy',
        ),
        migrations.AlterUniqueTogether(
            name='contentshare',
            unique_together={('content', 'shared_with_email')},
        ),
        migrations.AddField(
            model_name='contentshare',
            name='shared_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentshare',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='content.content'),
        ),
        migrations.AlterField(
            model_name='contentshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentshare',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Registration'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='contentshare',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='contentshare',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='contentshare',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='contentshare',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='contentshare',
            name='shared_with_user',
        ),
        migrations.RemoveField(
            model_name='contentshare',
            name='token_created_at',
        ),
    ]
